# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: npm install and build'

- script: |
    node node_modules/.bin/webdriver-manager update --versions.chrome=84.0.4147.135
    ng e2e --webdriverUpdate=false
    ls -l
    pwd
    echo "E2E testing done"
  displayName: 'e2e testing'

- script: |
    echo "Working directory."
    pwd
    echo "directory content."
    ls -al
    echo "###########################Contents of the Dist folder are listed below##########################"
    cd e2e && ls -l
  displayName: 'Install Dependencies'
