# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@latest
    npm cache clean --force
    npm i
    ng build --prod
  displayName: 'Install Node.js'


- script: |
    echo "E2E testing"
    ng e2e
    echo "E2E testing done"
  displayName: 'e2e testing'

- script: |
    echo "Working directory."
    pwd
    echo "directory content."
    ls -al
    echo "###########################Contents of the Dist folder are listed below##########################"
    cd dist && ls -l
  displayName: 'Install Dependencies'
